Name: Mayank Bhansali
Roll no.: J008

    
    
    
Assignment 2

In [1]:
import numpy as np
import time

In [2]:
mat1 = np.arange(11, 20, 1)
A = mat1.reshape(3, 3)

In [3]:
mat2 = np.arange(10, 19, 1)
B = mat2.reshape(3, 3)

In [4]:
mat3 = np.arange(0, 9, 1)
C = mat3.reshape(3, 3)

A.B != B.A

In [5]:
np.dot(A, B)

array([[474, 510, 546],
       [591, 636, 681],
       [708, 762, 816]])

In [6]:
np.dot(B, A)

array([[468, 501, 534],
       [594, 636, 678],
       [720, 771, 822]])

We can see that A.B is not equal to B.A

A(BC)!=(AB)C

In [7]:
A.dot(B.dot(C))

array([[ 4806,  6336,  7866],
       [ 5994,  7902,  9810],
       [ 7182,  9468, 11754]])

In [8]:
(A.dot(B)).dot(C)

array([[ 4806,  6336,  7866],
       [ 5994,  7902,  9810],
       [ 7182,  9468, 11754]])

We can see that A(BC) is not equal to (AB)C

A(B+C)=AB+BC

In [9]:
A.dot(B+C)

array([[ 588,  660,  732],
       [ 732,  822,  912],
       [ 876,  984, 1092]])

In [10]:
(A.dot(B))+(A.dot(C))

array([[ 588,  660,  732],
       [ 732,  822,  912],
       [ 876,  984, 1092]])

We can see that A(B+C) is equal to AB+BC

AI=IA

In [11]:
A=np.random.randint(0,5,(6,6))
I=np.identity(6)

In [12]:
A.dot(I)

array([[3., 0., 4., 0., 0., 1.],
       [3., 2., 3., 2., 1., 3.],
       [4., 0., 4., 4., 0., 0.],
       [3., 4., 1., 3., 0., 1.],
       [2., 3., 0., 2., 0., 2.],
       [0., 3., 3., 2., 4., 0.]])

In [13]:
I.dot(A)

array([[3., 0., 4., 0., 0., 1.],
       [3., 2., 3., 2., 1., 3.],
       [4., 0., 4., 4., 0., 0.],
       [3., 4., 1., 3., 0., 1.],
       [2., 3., 0., 2., 0., 2.],
       [0., 3., 3., 2., 4., 0.]])

We can see that A.I=I.A

In [14]:
matrix=np.random.randint(0,20,(5,5))

In [15]:
matrix_inverted=np.linalg.inv(matrix)

In [16]:
matrix,matrix_inverted

(array([[ 5,  3, 16, 17, 10],
        [ 0, 12,  4,  0,  1],
        [ 8,  0,  7,  7, 13],
        [ 4,  8,  8, 11,  7],
        [ 3,  8,  7, 12,  7]]),
 array([[-1.50705799e-01, -1.89397786e-01, -5.29095156e-02,
          1.15497106e+00, -8.14359703e-01],
        [-4.41758911e-02,  4.48867675e-02, -9.44450086e-03,
          7.37280390e-02,  5.07768864e-04],
        [ 1.21864527e-01,  8.30709861e-02, -8.42896314e-03,
         -3.09739007e-02, -1.39331776e-01],
        [-2.88412715e-02, -1.06326800e-01, -6.13384787e-02,
          1.23997156e-01,  4.63085204e-02],
        [ 4.26525845e-02,  1.29074845e-01,  1.47049863e-01,
         -7.60840865e-01,  5.51233878e-01]]))

Addition using for loop

In [25]:
mat1=np.random.randint(100,size=(5,5))
mat2=np.random.randint(100,size=(5,5))

In [27]:
start=time.time()
for i in range(len(mat1)):
    for j in range(len(mat1)):
        mat1[i][j]+=mat1[i][j]+1
print(time.time()-start)

0.0003147125244140625


Addition using inbuilt function

In [29]:
start=time.time()
ans=np.add(mat2,mat2)
print(time.time()-start)

0.00914907455444336
